var NavEvent=NavEvent||{REVISION:"0.0.5.0-2016-11.14"};NavEvent.Url="ws://"+window.location.hostname+":9090";localStorage.serverIP=window.location.hostname;NavEvent.ros=new ROSLIB.Ros;NavEvent.ros.connect(NavEvent.Url);NavEvent.data={Connect:!1,WaypointList:[],TrajectoryList:[],WaypointsHtml:"<option value='-1'>\u7a7a</option>",LoginName:"",LoginPassword:"",LockScreen:!1,NavigationMode:null,goalTest:null,SaveMapEditFlag:!1,MachineModel:"NONE",goalMarkList:[],CreateMapFlag:!1,Auth:"",CurrentPositionName:""};
NavEvent.MachineEnum={NULL:"NONE",exhibt:"exhibt",ster:"ster",liebao:"liebao"};NavEvent.diagnosticsNameEnum={Ros_Mode:"/Other/ros_mode"};
NavEvent.CmdEnum={Navigation:"navigation",Gmapping:"gmapping",Cancel:"cancel",Coverting:"converting",GamppingPose:"gmapping_pose",SaveMap:"save_map",SaveMapEdit:"save_map_edit",SaveAsMap:"save_as_map",SaveAsMapEdit:"save_as_map_edit",LoadMap:"load_map",LoadMapEdit:"load_map_edit",Busy:"busy",NULL:"",ChargeUp:'rostopic pub -1 /auto_charge std_msgs/Byte "1"',ChargeDown:'rostopic pub -1 /auto_charge std_msgs/Byte "0"',Joystick:'_JOYSTICK=`rosnode list | grep teleop_joystic`; if [[ -n $_JOYSTICK ]]; then _FB="joy_on"; else _FB="joy_off"; fi; rostopic pub -1 /shell_feedback std_msgs/String $_FB',
JoystickOn:"roslaunch bringup teleop_joystick.launch",JoystickOff:"rosnode kill /teleop_joystick",MapSaveStaus:'roslaunch bringup map_edit_as_saver.launch; rostopic pub -1 /shell_feedback std_msgs/String "map_edit_ok"',Version:"version",Version1:"_RC=`grep '\\''|'\\'' ~/catkin_ws/README.md`;_FB=`echo $_RC | awk -F '\\''|'\\'' '\\''{print $10}'\\''`;_FB=`echo version:$_FB | awk -F '\\'' '\\'' '\\''{print $1$2}'\\''`;rostopic pub -1 /shell_feedback std_msgs/String $_FB;unset _FB; unset _RC;",PLCopen:'rostopic pub -1 /waypoint_user_pub std_msgs/String "wangjin_open"',
PLCclose:'rostopic pub -1 /waypoint_user_pub std_msgs/String "wangjin_close"',PLCstatus:'rostopic pub -1 /waypoint_user_pub std_msgs/String "wangjin_status"',Userauth:"user_auth",Map_Select:"dbparam-select",Map_Delete:"dbparam-delete",Map_Update:"dbparam-update",Map_Insert:"dbparam-insert",Update:"update"};NavEvent.Msg=new ROSLIB.Message({data:NavEvent.CmdEnum.NULL});NavEvent.modeTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/system_mode",messageType:"std_msgs/String"});
NavEvent.cmdTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/cmd_string",messageType:"std_msgs/String"});NavEvent.shellTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/shell_string",messageType:"std_msgs/String"});NavEvent.imuTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/mobile_imu",messageType:"sensor_msgs/Imu"});NavEvent.velTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/cmd_vel",messageType:"geometry_msgs/Twist"});NavEvent.odomTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/odom",messageType:"nav_msgs/Odometry"});
NavEvent.poseTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/robot_pose",messageType:"geometry_msgs/Pose",throttle_rate:100});NavEvent.diagnosticsTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/diagnostics_agg",messageType:"diagnostic_msgs/DiagnosticArray",throttle_rate:100});NavEvent.MapEditTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/map_edit",messageType:"nav_msgs/OccupancyGrid",compression:"png"});NavEvent.MapEditAsTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/map_edit_as",messageType:"nav_msgs/OccupancyGrid"});
NavEvent.WaypointTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/waypoints",messageType:"yocs_msgs/WaypointList"});NavEvent.TrajectoryTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/trajectories",messageType:"yocs_msgs/TrajectoryList"});NavEvent.WaypointAddTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/waypoint_add",messageType:"yocs_msgs/Waypoint"});NavEvent.WaypointRemoveTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/waypoint_remove",messageType:"yocs_msgs/Waypoint"});
NavEvent.TrajectoryAddTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/trajectory_add",messageType:"yocs_msgs/Trajectory"});NavEvent.TrajectoryRemoveTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/trajectory_remove",messageType:"yocs_msgs/Trajectory"});NavEvent.NavCtrlTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/nav_ctrl",messageType:"yocs_msgs/NavigationControl"});NavEvent.NavCtrlStatusTopic=new ROSLIB.Topic({ros:NavEvent.ros,name:"/nav_ctrl_status",messageType:"yocs_msgs/NavigationControlStatus"});
NavEvent.ShellFeedback=new ROSLIB.Topic({ros:NavEvent.ros,name:"/shell_feedback",messageType:"std_msgs/String"});NavEvent.actionClient=new ROSLIB.ActionClient({ros:NavEvent.ros,actionName:"move_base_msgs/MoveBaseAction",serverName:"/move_base"});NavEvent.ros.on("connection",function(){NavEvent.data.Connect=!0;$(".networkstatus").buttonMarkup({icon:"hrg-networksuccess"})});
NavEvent.ros.on("close",function(){NavEvent.data.Connect=!1;$(".networkstatus").buttonMarkup({icon:"hrg-networkerror"});sweetAlert("\u7f51\u7edc\u51fa\u9519","","error")});NavEvent.Msg=function(a){return new ROSLIB.Message({data:a})};NavEvent.MapMessage=function(a,b){return new ROSLIB.Message({header:{frame_id:"/map",seq:0},info:a,data:b})};NavEvent.pose=function(a,b,c,d){return new ROSLIB.Pose({position:{x:a,y:b,z:0},orientation:{x:0,y:0,z:c,w:d}})};
NavEvent.WaypointMessage=function(a,b,c,d,e,f){return new ROSLIB.Message({header:{frame_id:f},close_enough:c,goal_timeout:d,failure_mode:e,name:a,pose:b})};NavEvent.TrajectoryMessage=function(a,b){return new ROSLIB.Message({name:a,waypoints:b})};NavEvent.NavCtrlMessage=function(a,b){return new ROSLIB.Message({control:a,goal_name:b})};NavEvent.goal=function(a){return new ROSLIB.Goal({actionClient:NavEvent.actionClient,goalMessage:{target_pose:{header:{frame_id:"/map"},pose:a}}})};
NavEvent.twistMessage=function(a,b){return new ROSLIB.Message({linear:{x:a,y:0,z:0},angular:{x:0,y:0,z:b}})};
NavEvent.WorkPool=function(){this.LoadMap=function(a,b,c){a=new ROS2D.Viewer({divID:c,width:a,height:b,background:"url('images/bg1.jpg')"});NAV2D.OccupancyGridClientNav({ros:NavEvent.ros,rootObject:a.scene,continuous:!0,withOrientation:!0,viewer:a,serverName:"/move_base"});return a.scene};this.RemoveMap=function(a){$("#"+a+" canvas").remove()};this.Gmapping=function(){if(NavEvent.data.NavigationMode==NavEvent.CmdEnum.Gmapping)return!1;var a=new NavEvent.Msg(NavEvent.CmdEnum.Gmapping);NavEvent.cmdTopic.publish(a);
return!0};this.Navigation=function(){if(NavEvent.data.NavigationMode==NavEvent.CmdEnum.Navigation)return!1;var a=new NavEvent.Msg(NavEvent.CmdEnum.Navigation);NavEvent.cmdTopic.publish(a);return!0};this.SaveMap=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.GamppingPose);NavEvent.cmdTopic.publish(a);a=new NavEvent.Msg(NavEvent.CmdEnum.SaveMap);NavEvent.cmdTopic.publish(a)};this.SaveMapEdit=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.SaveAsMapEdit);NavEvent.cmdTopic.publish(a);a=MapEditDataConvert();
a=new NavEvent.MapMessage(NavEvent.MapEditMessage.info,a);NavEvent.MapEditAsTopic.publish(a)};this.Cancel=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.Cancel);NavEvent.cmdTopic.publish(a)};this.CloseHandle=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.JoystickOff);NavEvent.shellTopic.publish(a);a=new NavEvent.Msg(NavEvent.CmdEnum.Joystick);NavEvent.shellTopic.publish(a)};this.OpenHandle=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.JoystickOn);NavEvent.shellTopic.publish(a);a=new NavEvent.Msg(NavEvent.CmdEnum.Joystick);
NavEvent.shellTopic.publish(a)};this.goPostion=function(a){null!=NavEvent.data.goalTest&&(NavEvent.data.goalTest=null);NavEvent.data.goalTest=new NavEvent.goal(a);NavEvent.data.goalTest.send();NavEvent.data.goalTest.on("status",goalCallback)};this.ChargeUp=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.ChargeUp);NavEvent.shellTopic.publish(a)};this.ChargeDown=function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.ChargeDown);NavEvent.shellTopic.publish(a)};this.subscribeDiagnostics=function(a){NavEvent.diagnosticsTopic.subscribe(a)};
this.unsubscribeDiagnostics=function(a){NavEvent.diagnosticsTopic.unsubscribe(a)};this.subscribeMapEdit=function(){NavEvent.MapEditTopic.subscribe(MapEditCallBack)};this.subscribeShellFeedback=function(a){NavEvent.ShellFeedback.subscribe(a)};this.DrawPoint=function(a,b,c){var d=new ROS2D.NavigationArrow({size:15,strokeSize:1,fillColor:createjs.Graphics.getRGB(255,64,128,.66),pulse:!0});d.x=b.position.x;d.y=b.position.y;d.rotation=a.rosQuaternionToGlobalTheta(b.orientation);d.scaleX=1/a.scaleX;d.scaleY=
1/a.scaleY;c?a.addChild(d):a.removeChild(d);return d};this.DirectionControl=function(a){if(NavEvent.data.Connect){var b=0,c=0;switch(a){case "up":b=.25;c=0;break;case "down":b=-.25;c=0;break;case "left":b=0;c=.5;break;case "right":b=0;c=-.5;break;case "stop":c=b=0}NavEvent.velTopic.publish(new NavEvent.twistMessage(b,c))}}};function goalCallback(a){switch(a.status){case 3:NavEvent.data.goalTest.off("status",goalCallback);break;case 4:NavEvent.data.goalTest.off("status",goalCallback)}}
function MapEditDataConvert(){for(var a=[],b=document.getElementById("map-edit-canvas").getContext("2d"),c=document.getElementById("map-edit-canvas"),b=b.getImageData(0,0,c.width,c.height),d=0;d<c.height;d++)for(var e=0;e<c.width;e++){var f=e+(c.height-d-1)*c.width;switch(b.data[4*(e+d*c.width)]){case 0:a[f]=100;break;case 255:a[f]=0;break;case 127:a[f]=-1;break;default:a[f]=100}}return a}
function MapEditCallBack(a){$("#map-edit-canvas-father img").hide();NavEvent.MapEditTopic.unsubscribe(MapEditCallBack);NavEvent.MapEditMessage=a;var b=document.getElementById("map-edit-canvas"),c=b.getContext("2d");b.width=a.info.width;b.height=a.info.height;for(var d=c.createImageData(b.width,b.height),e=0;e<b.height;e++)for(var f=0;f<b.width;f++){var g=a.data[f+(b.height-e-1)*b.width],g=100===g?0:0===g?255:127,h=4*(f+e*b.width);d.data[h]=g;d.data[++h]=g;d.data[++h]=g;d.data[++h]=255}c.putImageData(d,
0,0);$("#hrg-map-wizard-third").css("background","grey");$("#map-edit-canvas").show();a=document.getElementById("map-edit-canvas-father");a.scrollLeft=a.scrollWidth/2-100;a.scrollTop=a.scrollHeight/2-100}Array.prototype.del=function(a){if(isNaN(a)||a>=this.length)return!1;for(var b=0,c=0;b<this.length;b++)this[b]!=this[a]&&(this[c++]=this[b]);--this.length};var NavJobs=new NavEvent.WorkPool;