var ROS2D=ROS2D||{REVISION:"0.8.0-SNAPSHOT"},myScene;createjs.Stage.prototype.globalToRos=function(a,b){return new ROSLIB.Vector3({x:(a-this.x)/this.scaleX,y:(this.y-b)/this.scaleY})};createjs.Stage.prototype.rosToGlobal=function(a){return{x:a.x*this.scaleX+this.x,y:a.y*this.scaleY+this.y}};createjs.Stage.prototype.rosQuaternionToGlobalTheta=function(a){var b=a.y,c=a.z;return 180*-Math.atan2(2*(a.w*c+a.x*b),1-2*(b*b+c*c))/Math.PI};
ROS2D.ImageMap=function(a){a=a||{};var b=a.message;a=a.image;this.pose=new ROSLIB.Pose({position:b.origin.position,orientation:b.origin.orientation});this.width=b.width;this.height=b.height;createjs.Bitmap.call(this,a);this.y=-this.height*b.resolution;this.scaleY=this.scaleX=b.resolution;this.width*=this.scaleX;this.height*=this.scaleY;this.x+=this.pose.position.x;this.y-=this.pose.position.y};ROS2D.ImageMap.prototype.__proto__=createjs.Bitmap.prototype;
ROS2D.ImageMapClient=function(a){var b=this;a=a||{};var c=a.ros,d=a.topic||"/map_metadata";this.image=a.image;this.rootObject=a.rootObject||new createjs.Container;this.currentImage=new createjs.Shape;var f=new ROSLIB.Topic({ros:c,name:d,messageType:"nav_msgs/MapMetaData"});f.subscribe(function(a){f.unsubscribe();b.currentImage=new ROS2D.ImageMap({message:a,image:b.image});b.rootObject.addChild(b.currentImage);b.rootObject.addChild(new ROS2D.Grid({size:1}));b.emit("change")})};
ROS2D.ImageMapClient.prototype.__proto__=EventEmitter2.prototype;
ROS2D.OccupancyGrid=function(a){a=a||{};a=a.message;var b=document.createElement("canvas"),c=b.getContext("2d");this.pose=new ROSLIB.Pose({position:a.info.origin.position,orientation:a.info.origin.orientation});this.width=a.info.width;this.height=a.info.height;b.width=this.width;b.height=this.height;(new Date).getTime();for(var d=c.createImageData(this.width,this.height),f=0;f<this.height;f++)for(var h=0;h<this.width;h++){var e=a.data[h+(this.height-f-1)*this.width],e=100===e?0:0===e?255:127,g=4*
(h+f*this.width);d.data[g]=e;d.data[++g]=e;d.data[++g]=e;d.data[++g]=255}c.putImageData(d,0,0);createjs.Bitmap.call(this,b);$("#nav-load").hide();b=document.getElementById(CanvasID);b.scrollLeft=b.scrollWidth/2-100;b.scrollTop=b.scrollHeight/2-100;this.y=-this.height*a.info.resolution;this.scaleY=this.scaleX=a.info.resolution;this.width*=this.scaleX;this.height*=this.scaleY;this.x+=this.pose.position.x;this.y-=this.pose.position.y};ROS2D.OccupancyGrid.prototype.__proto__=createjs.Bitmap.prototype;
ROS2D.OccupancyGridClient=function(a){var b=this;a=a||{};var c=a.ros,d=a.topic||"/map";this.continuous=a.continuous;this.rootObject=a.rootObject||new createjs.Container;this.currentGrid=new createjs.Shape;this.rootObject.addChild(this.currentGrid);this.rootObject.addChild(new ROS2D.Grid({size:1}));var f=new ROSLIB.Topic({ros:c,name:d,messageType:"nav_msgs/OccupancyGrid",compression:"png"});(new Date).getTime();f.subscribe(function(a){var c=null;b.currentGrid&&(c=b.rootObject.getChildIndex(b.currentGrid),
b.rootObject.removeChild(b.currentGrid));b.currentGrid=new ROS2D.OccupancyGrid({message:a});null!==c?b.rootObject.addChildAt(b.currentGrid,c):b.rootObject.addChild(b.currentGrid);b.emit("change");b.continuous||f.unsubscribe()})};ROS2D.OccupancyGridClient.prototype.__proto__=EventEmitter2.prototype;
ROS2D.OccupancyGridSrvClient=function(a){var b=this;a=a||{};var c=a.ros,d=a.service||"/static_map";this.rootObject=a.rootObject||new createjs.Container;this.currentGrid=null;(new ROSLIB.Service({ros:c,name:d,serviceType:"nav_msgs/GetMap",compression:"png"})).callService(new ROSLIB.ServiceRequest,function(a){b.currentGrid&&b.rootObject.removeChild(b.currentGrid);b.currentGrid=new ROS2D.OccupancyGrid({message:a.map});b.rootObject.addChild(b.currentGrid);b.emit("change",b.currentGrid)})};
ROS2D.OccupancyGridSrvClient.prototype.__proto__=EventEmitter2.prototype;
ROS2D.ArrowShape=function(a){var b=this;a=a||{};var c=a.size||10,d=a.strokeSize||3,f=a.strokeColor||createjs.Graphics.getRGB(0,0,0),h=a.fillColor||createjs.Graphics.getRGB(255,0,0);a=a.pulse;var e=new createjs.Graphics,g=c/3,l=2*g/3;e.setStrokeStyle(d);e.beginStroke(f);e.moveTo(0,0);e.lineTo(c-g,0);e.beginFill(h);e.moveTo(c,0);e.lineTo(c-g,l/2);e.lineTo(c-g,-l/2);e.closePath();e.endFill();e.endStroke();createjs.Shape.call(this,e);if(a){var m=0,k=!0;createjs.Ticker.addEventListener("tick",function(){k?
(b.scaleX*=1.035,b.scaleY*=1.035,k=10>++m):(b.scaleX/=1.035,b.scaleY/=1.035,k=0>--m)})}};ROS2D.ArrowShape.prototype.__proto__=createjs.Shape.prototype;
ROS2D.Grid=function(a){a=a||{};var b=a.size||10,c=a.cellSize||.1,d=a.lineWidth||.001;a=new createjs.Graphics;a.setStrokeStyle(5*d);a.beginStroke(createjs.Graphics.getRGB(0,0,0));a.beginFill(createjs.Graphics.getRGB(255,0,0));a.moveTo(-b*c,0);a.lineTo(b*c,0);a.moveTo(0,-b*c);a.lineTo(0,b*c);a.endFill();a.endStroke();a.setStrokeStyle(d);a.beginStroke(createjs.Graphics.getRGB(0,0,0));a.beginFill(createjs.Graphics.getRGB(255,0,0));for(d=-b;d<=b;d++)a.moveTo(-b*c,d*c),a.lineTo(b*c,d*c),a.moveTo(d*c,-b*
c),a.lineTo(d*c,b*c);a.endFill();a.endStroke();createjs.Shape.call(this,a)};ROS2D.Grid.prototype.__proto__=createjs.Shape.prototype;
ROS2D.NavigationArrow=function(a){var b=this;a=a||{};var c=a.size||10,d=a.strokeSize||3,f=a.strokeColor||createjs.Graphics.getRGB(0,0,0),h=a.fillColor||createjs.Graphics.getRGB(255,0,0);a=a.pulse;var e=new createjs.Graphics;e.setStrokeStyle(d);e.moveTo(-c/2,-c/2);e.beginStroke(f);e.beginFill(h);e.lineTo(c,0);e.lineTo(-c/2,c/2);e.closePath();e.endFill();e.endStroke();createjs.Shape.call(this,e);if(a){var g=0,l=!0;createjs.Ticker.addEventListener("tick",function(){l?(b.scaleX*=1.035,b.scaleY*=1.035,
l=10>++g):(b.scaleX/=1.035,b.scaleY/=1.035,l=0>--g)})}};ROS2D.NavigationArrow.prototype.__proto__=createjs.Shape.prototype;
ROS2D.NavigationImage=function(a){var b=this;a=a||{};var c=a.size||10,d=a.image,f=a.pulse,h=a.alpha||1,e={},g=new Image;g.onload=function(){createjs.Bitmap.call(b,g);var a=c/g.width;b.alpha=h;b.scaleX=a;b.scaleY=a;b.regY=b.image.height/2;b.regX=b.image.width/2;e.rotation=b.rotation;Object.defineProperty(b,"rotation",{get:function(){return e.rotation+90},set:function(a){e.rotation=a}});if(f){var d=0,k=!0;createjs.Ticker.addEventListener("tick",function(){k?(b.scaleX*=1.02,b.scaleY*=1.02,k=10>++d):
(b.scaleX/=1.02,b.scaleY/=1.02,k=0>--d)})}};g.src=d};ROS2D.NavigationImage.prototype.__proto__=createjs.Bitmap.prototype;
ROS2D.PathShape=function(a){a=a||{};var b=a.path;this.strokeSize=a.strokeSize||3;this.strokeColor=a.strokeColor||createjs.Graphics.getRGB(0,0,0);this.graphics=new createjs.Graphics;if(null!==b&&"undefined"!==typeof b){this.graphics.setStrokeStyle(this.strokeSize);this.graphics.beginStroke(this.strokeColor);this.graphics.moveTo(b.poses[0].pose.position.x/this.scaleX,b.poses[0].pose.position.y/-this.scaleY);for(a=1;a<b.poses.length;++a)this.graphics.lineTo(b.poses[a].pose.position.x/this.scaleX,b.poses[a].pose.position.y/
-this.scaleY);this.graphics.endStroke()}createjs.Shape.call(this,this.graphics)};
ROS2D.PathShape.prototype.setPath=function(a){this.graphics.clear();if(null!==a&&"undefined"!==typeof a){this.graphics.setStrokeStyle(this.strokeSize);this.graphics.beginStroke(this.strokeColor);this.graphics.moveTo(a.poses[0].pose.position.x/this.scaleX,a.poses[0].pose.position.y/-this.scaleY);for(var b=1;b<a.poses.length;++b)this.graphics.lineTo(a.poses[b].pose.position.x/this.scaleX,a.poses[b].pose.position.y/-this.scaleY);this.graphics.endStroke()}};ROS2D.PathShape.prototype.__proto__=createjs.Shape.prototype;
ROS2D.PolygonMarker=function(a){a=a||{};this.lineSize=a.lineSize||3;this.lineColor=a.lineColor||createjs.Graphics.getRGB(0,0,255,.66);this.pointSize=a.pointSize||10;this.pointColor=a.pointColor||createjs.Graphics.getRGB(255,0,0,.66);this.fillColor=a.pointColor||createjs.Graphics.getRGB(0,255,0,.33);this.lineCallBack=a.lineCallBack;this.pointCallBack=a.pointCallBack;this.pointContainer=new createjs.Container;this.lineContainer=new createjs.Container;this.fillShape=new createjs.Shape;createjs.Container.call(this);
this.addChild(this.fillShape);this.addChild(this.lineContainer);this.addChild(this.pointContainer)};ROS2D.PolygonMarker.prototype.createLineShape=function(a,b){var c=new createjs.Shape;this.editLineShape(c,a,b);var d=this;c.addEventListener("mousedown",function(a){null!==d.lineCallBack&&"undefined"!==typeof d.lineCallBack&&d.lineCallBack("mousedown",a,d.lineContainer.getChildIndex(a.target))});return c};
ROS2D.PolygonMarker.prototype.editLineShape=function(a,b,c){a.graphics.clear();a.graphics.setStrokeStyle(this.lineSize);a.graphics.beginStroke(this.lineColor);a.graphics.moveTo(b.x,b.y);a.graphics.lineTo(c.x,c.y)};
ROS2D.PolygonMarker.prototype.createPointShape=function(a){var b=new createjs.Shape;b.graphics.beginFill(this.pointColor);b.graphics.drawCircle(0,0,this.pointSize);b.x=a.x;b.y=-a.y;var c=this;b.addEventListener("mousedown",function(a){null!==c.pointCallBack&&"undefined"!==typeof c.pointCallBack&&c.pointCallBack("mousedown",a,c.pointContainer.getChildIndex(a.target))});return b};
ROS2D.PolygonMarker.prototype.addPoint=function(a){a=this.createPointShape(a);this.pointContainer.addChild(a);var b=this.pointContainer.getNumChildren();if(!(2>b)&&3>b){var c=this.createLineShape(this.pointContainer.getChildAt(b-2),a);this.lineContainer.addChild(c)}2<b&&this.editLineShape(this.lineContainer.getChildAt(b-2),this.pointContainer.getChildAt(b-2),a);1<b&&(a=this.createLineShape(a,this.pointContainer.getChildAt(0)),this.lineContainer.addChild(a));this.drawFill()};
ROS2D.PolygonMarker.prototype.remPoint=function(a){a=a instanceof createjs.Shape?this.pointContainer.getChildIndex(a):a;var b=this.pointContainer.getNumChildren();2>b||(3>b?this.lineContainer.removeAllChildren():(this.editLineShape(this.lineContainer.getChildAt((a-1+b)%b),this.pointContainer.getChildAt((a-1+b)%b),this.pointContainer.getChildAt((a+1)%b)),this.lineContainer.removeChildAt(a)));this.pointContainer.removeChildAt(a);this.drawFill()};
ROS2D.PolygonMarker.prototype.movePoint=function(a,b){var c,d;a instanceof createjs.Shape?(c=this.pointContainer.getChildIndex(a),d=a):(c=a,d=this.pointContainer.getChildAt(c));d.x=b.x;d.y=-b.y;var f=this.pointContainer.getNumChildren();if(1<f){var h=this.lineContainer.getChildAt((c-1+f)%f);this.editLineShape(h,this.pointContainer.getChildAt((c-1+f)%f),d);h=this.lineContainer.getChildAt(c);this.editLineShape(h,d,this.pointContainer.getChildAt((c+1)%f))}this.drawFill()};
ROS2D.PolygonMarker.prototype.splitLine=function(a){var b;a instanceof createjs.Shape?b=this.lineContainer.getChildIndex(a):(b=a,a=this.lineContainer.getChildAt(b));var c=this.pointContainer.getNumChildren(),d=this.pointContainer.getChildAt(b).x,f=this.pointContainer.getChildAt(b).y,h=this.pointContainer.getChildAt((b+1)%c).x,e=this.pointContainer.getChildAt((b+1)%c).y,d=new ROSLIB.Vector3({x:(d+h)/2,y:-((f+e)/2)}),d=this.createPointShape(d);this.pointContainer.addChildAt(d,b+1);++c;c=this.createLineShape(d,
this.pointContainer.getChildAt((b+2)%c));this.lineContainer.addChildAt(c,b+1);this.editLineShape(a,this.pointContainer.getChildAt(b),d);this.drawFill()};
ROS2D.PolygonMarker.prototype.drawFill=function(){var a=this.pointContainer.getNumChildren();if(2<a){var b=this.fillShape.graphics;b.clear();b.setStrokeStyle(0);b.moveTo(this.pointContainer.getChildAt(0).x,this.pointContainer.getChildAt(0).y);b.beginStroke();b.beginFill(this.fillColor);for(var c=1;c<a;++c)b.lineTo(this.pointContainer.getChildAt(c).x,this.pointContainer.getChildAt(c).y);b.closePath();b.endFill();b.endStroke()}else this.fillShape.graphics.clear()};
ROS2D.PolygonMarker.prototype.__proto__=createjs.Container.prototype;
ROS2D.TraceShape=function(a){a=a||{};var b=a.pose;this.strokeSize=a.strokeSize||3;this.strokeColor=a.strokeColor||createjs.Graphics.getRGB(0,0,0);this.maxPoses=a.maxPoses||100;this.minDist=a.minDist||.05;this.minDist*=this.minDist;this.poses=[];this.graphics=new createjs.Graphics;this.graphics.setStrokeStyle(this.strokeSize);this.graphics.beginStroke(this.strokeColor);null!==b&&"undefined"!==typeof b&&this.poses.push(b);createjs.Shape.call(this,this.graphics)};
ROS2D.TraceShape.prototype.addPose=function(a){var b=this.poses.length-1;if(0>b)this.poses.push(a),this.graphics.moveTo(a.position.x/this.scaleX,a.position.y/-this.scaleY);else{var c=a.position.x-this.poses[b].position.x,b=a.position.y-this.poses[b].position.y;c*c+b*b>this.minDist&&(this.graphics.lineTo(a.position.x/this.scaleX,a.position.y/-this.scaleY),this.poses.push(a))}0<this.maxPoses&&this.maxPoses<this.poses.length&&this.popFront()};
ROS2D.TraceShape.prototype.popFront=function(){if(0<this.poses.length){this.poses.shift();this.graphics.clear();this.graphics.setStrokeStyle(this.strokeSize);this.graphics.beginStroke(this.strokeColor);this.graphics.lineTo(this.poses[0].position.x/this.scaleX,this.poses[0].position.y/-this.scaleY);for(var a=1;a<this.poses.length;++a)this.graphics.lineTo(this.poses[a].position.x/this.scaleX,this.poses[a].position.y/-this.scaleY)}};ROS2D.TraceShape.prototype.__proto__=createjs.Shape.prototype;
ROS2D.PanView=function(a){a=a||{};this.rootObject=a.rootObject;this.stage=this.rootObject instanceof createjs.Stage?this.rootObject:this.rootObject.getStage();this.startPos=new ROSLIB.Vector3};ROS2D.PanView.prototype.startPan=function(a,b){this.startPos.x=a;this.startPos.y=b};ROS2D.PanView.prototype.pan=function(a,b){this.stage.x+=a-this.startPos.x;this.startPos.x=a;this.stage.y+=b-this.startPos.y;this.startPos.y=b};var CanvasID="";
ROS2D.Viewer=function(a){a=a||{};var b=a.divID;CanvasID=b;this.width=a.width;this.height=a.height;a=a.background||"#111111";var c=document.createElement("canvas");c.width=this.width;c.height=this.height;c.style.background=a;c.style.display="none";$("#"+b).append(c);$("#"+b+" canvas").slideUp("slow",function(){$(this).show(500,function(){$("#nav-load").show()})});myScene=this.scene=new createjs.Stage(c);this.scene.y=this.height;document.getElementById(b).appendChild(c);createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",
this.scene)};ROS2D.Viewer.prototype.addObject=function(a){this.scene.addChild(a)};ROS2D.Viewer.prototype.scaleToDimensions=function(a,b){this.scene.x="undefined"!==typeof this.scene.x_prev_shift?this.scene.x_prev_shift:this.scene.x;this.scene.y="undefined"!==typeof this.scene.y_prev_shift?this.scene.y_prev_shift:this.scene.y;this.scene.scaleX=this.width/a;this.scene.scaleY=this.height/b};
ROS2D.Viewer.prototype.shift=function(a,b){this.scene.x_prev_shift=this.scene.x;this.scene.y_prev_shift=this.scene.y;this.scene.x-=a*this.scene.scaleX;this.scene.y+=b*this.scene.scaleY};ROS2D.ZoomView=function(a){a=a||{};this.rootObject=a.rootObject;this.minScale=a.minScale||.001;this.stage=this.rootObject instanceof createjs.Stage?this.rootObject:this.rootObject.getStage();this.center=new ROSLIB.Vector3;this.startShift=new ROSLIB.Vector3;this.startScale=new ROSLIB.Vector3};
ROS2D.ZoomView.prototype.startZoom=function(a,b){this.center.x=a;this.center.y=b;this.startShift.x=this.stage.x;this.startShift.y=this.stage.y;this.startScale.x=this.stage.scaleX;this.startScale.y=this.stage.scaleY};
ROS2D.ZoomView.prototype.zoom=function(a){this.startScale.x*a<this.minScale&&(a=this.minScale/this.startScale.x);this.startScale.y*a<this.minScale&&(a=this.minScale/this.startScale.y);this.stage.scaleX=this.startScale.x*a;this.stage.scaleY=this.startScale.y*a;this.stage.x=this.startShift.x-(this.center.x-this.startShift.x)*(this.stage.scaleX/this.startScale.x-1);this.stage.y=this.startShift.y-(this.center.y-this.startShift.y)*(this.stage.scaleY/this.startScale.y-1)};